const Games=(()=>{
  const FILES="abcdefgh";
  function toast(msg){if(window.Parlor&&window.Parlor.toast)window.Parlor.toast(msg)}
  function el(tag,cls,text){const n=document.createElement(tag);if(cls)n.className=cls;if(text)n.textContent=text;return n}

  const TTT={id:"tictactoe",title:"Tic-tac-toe",
    newState(){return{board:Array(9).fill(null),turn:"X",winner:null,winLine:null}},
    canMove(state,seat,idx){if(state.winner||state.board[idx])return false;return state.turn===(seat==="host"?"X":"O")},
    apply(state,{idx,seat}){if(!this.canMove(state,seat,idx))return state;const next={...state,board:state.board.slice()};next.board[idx]=state.turn;const w=winnerTTT(next.board);if(w){next.winner=w.mark;next.winLine=w.line}else if(next.board.every(Boolean))next.winner="draw";else next.turn=state.turn==="X"?"O":"X";return next},
    render(root,state,ctx){root.innerHTML="";const wrap=el("div","board-wrap");const grid=el("div","ttt");state.board.forEach((v,i)=>{const c=el("button","cell"+(v?" filled":"")+(state.winLine&&state.winLine.includes(i)?" win":""));c.textContent=v==="X"?"\u2715":v==="O"?"\u25cb":"";c.addEventListener("click",()=>ctx.tryMove({idx:i}));grid.appendChild(c)});wrap.appendChild(grid);root.appendChild(wrap)},
    status(state,seat){if(state.winner==="draw")return"Drawn game.";if(state.winner)return state.winner===(seat==="host"?"X":"O")?"You win.":"They win.";return state.turn===(seat==="host"?"X":"O")?"Your move.":"Their move."}
  };
  function winnerTTT(b){const lines=[[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]];for(const line of lines){const[a,c,d]=line;if(b[a]&&b[a]===b[c]&&b[a]===b[d])return{mark:b[a],line}}return null}

  const GLYPH={k:"\u265a",q:"\u265b",r:"\u265c",b:"\u265d",n:"\u265e",p:"\u265f"};
  const ChessGame={id:"chess",title:"Chess",
    newState(){const c=new Chess();return{fen:c.fen(),selected:null,last:null,promo:null,over:c.game_over()?resultOf(c):null}},
    apply(state,move){const c=new Chess(state.fen);const res=c.move(move);if(!res)return state;return{fen:c.fen(),selected:null,last:{from:res.from,to:res.to},promo:null,over:c.game_over()?resultOf(c):null}},
    render(root,state,ctx){const c=new Chess(state.fen);const board=c.board();const youWhite=ctx.seat==="host";const flipped=!youWhite;root.innerHTML="";const wrap=el("div","board-wrap");const grid=el("div","board");grid.style.gridTemplateColumns="repeat(8,1fr)";const selected=state.selected;const targets=selected?c.moves({square:selected,verbose:true}):[];const targetMap=Object.fromEntries(targets.map(m=>[m.to,m]));const ranks=flipped?[0,1,2,3,4,5,6,7]:[7,6,5,4,3,2,1,0];const files=flipped?[7,6,5,4,3,2,1,0]:[0,1,2,3,4,5,6,7];ranks.forEach(r=>{files.forEach(f=>{const sqName=FILES[f]+(r+1);const light=(r+f)%2===1;const cell=board[7-r][f];const sq=el("div","sq "+(light?"light":"dark"));if(selected===sqName)sq.classList.add("hi");if(state.last&&(state.last.from===sqName||state.last.to===sqName))sq.classList.add("last");if(targetMap[sqName])sq.classList.add(targetMap[sqName].captured?"cap":"move");if(cell){const span=el("span","piece "+(cell.color==="w"?"w":"b"));span.textContent=GLYPH[cell.type]||"";const mine=(youWhite&&cell.color==="w")||(!youWhite&&cell.color==="b");if(mine&&!state.over)span.classList.add("mine");sq.appendChild(span)}sq.addEventListener("click",()=>{if(state.over||state.promo)return;const myTurn=(youWhite&&c.turn()==="w")||(!youWhite&&c.turn()==="b");if(!myTurn)return;if(selected&&targetMap[sqName]){const mv=targetMap[sqName];if(mv.promotion){ctx.setLocal({...state,promo:{from:mv.from,to:mv.to}});return}ctx.tryMove({from:mv.from,to:mv.to});return}if(cell){const mine=(youWhite&&cell.color==="w")||(!youWhite&&cell.color==="b");ctx.setLocal({...state,selected:mine?sqName:null})}else ctx.setLocal({...state,selected:null})});grid.appendChild(sq)})});wrap.appendChild(grid);if(state.promo){const bar=el("div","promo");["q","r","b","n"].forEach(p=>{const b=document.createElement("button");b.textContent=GLYPH[p];b.className=youWhite?"piece w":"piece b";b.addEventListener("click",()=>ctx.tryMove({from:state.promo.from,to:state.promo.to,promotion:p}));bar.appendChild(b)});wrap.appendChild(bar)}root.appendChild(wrap)},
    status(state,seat){const c=new Chess(state.fen);if(state.over)return state.over;const youWhite=seat==="host";const myTurn=(youWhite&&c.turn()==="w")||(!youWhite&&c.turn()==="b");const side=c.turn()==="w"?"White":"Black";if(c.in_check())return(myTurn?"You are in check.":"They are in check.")+" "+side+" to move.";return myTurn?"Your move \u2014 "+side:"Their move \u2014 "+side}
  };
  function resultOf(c){if(c.in_checkmate())return c.turn()==="w"?"Black mates.":"White mates.";if(c.in_stalemate())return"Stalemate.";if(c.in_threefold_repetition())return"Draw by repetition.";if(c.insufficient_material())return"Draw \u2014 insufficient material.";if(c.in_draw())return"Drawn game.";return"Game over."}

  const Checkers={id:"checkers",title:"Checkers",
    newState(){const cells=Array(32).fill(null);for(let i=0;i<12;i++)cells[i]="r";for(let i=20;i<32;i++)cells[i]="b";return{cells,turn:"b",selected:null,over:null,last:null}},
    apply(state,{from,to,seat}){const color=seat==="host"?"b":"r";if(state.over||state.turn!==color)return state;const legal=legalMoves(state.cells,color);const mv=legal.find(m=>m.from===from&&m.to===to);if(!mv)return state;const cells=state.cells.slice();cells[to]=cells[from];cells[from]=null;mv.caps.forEach(c=>{cells[c]=null});const row=Math.floor(idxToRowCol(to).r);if(cells[to]==="b"&&row===0)cells[to]="B";if(cells[to]==="r"&&row===7)cells[to]="R";let turn=color==="b"?"r":"b",selected=null;if(mv.caps.length){const more=legalMovesFrom(cells,to).filter(m=>m.caps.length);if(more.length){turn=color;selected=to}}return{cells,turn,selected,over:winnerCheckers(cells),last:{from,to}}},
    render(root,state,ctx){const youBlack=ctx.seat==="host";const flipped=!youBlack;root.innerHTML="";const wrap=el("div","board-wrap");const grid=el("div","board");grid.style.gridTemplateColumns="repeat(8,1fr)";const selected=state.selected;const color=youBlack?"b":"r";const all=state.turn===color?legalMoves(state.cells,color):[];const fromMoves=selected==null?[]:all.filter(m=>m.from===selected);const dests=new Set(fromMoves.map(m=>m.to));const capDests=new Set(fromMoves.filter(m=>m.caps.length).map(m=>m.to));const rows=flipped?[0,1,2,3,4,5,6,7]:[7,6,5,4,3,2,1,0];const cols=flipped?[7,6,5,4,3,2,1,0]:[0,1,2,3,4,5,6,7];rows.forEach(r=>{cols.forEach(c=>{const dark=(r+c)%2===1;const sq=el("div","sq "+(dark?"dark":"light"));if(dark){const idx=squareIndex(r,c);if(state.last&&(state.last.from===idx||state.last.to===idx))sq.classList.add("last");if(selected===idx)sq.classList.add("hi");if(dests.has(idx))sq.classList.add(capDests.has(idx)?"cap":"move");const p=state.cells[idx];if(p){const span=el("span","piece");const isKing=p==="B"||p==="R";const isBlack=p==="b"||p==="B";span.textContent=isKing?"\u25c9":"\u25cf";span.style.color=isBlack?"#1a1a16":"#b33a2b";span.style.fontSize="0.85em";if(isBlack)span.style.webkitTextStroke="2px #e8dcc4";const mine=(youBlack&&isBlack)||(!youBlack&&!isBlack);if(mine&&!state.over)span.classList.add("mine");sq.appendChild(span)}sq.addEventListener("click",()=>{if(state.over||state.turn!==color)return;if(selected!=null&&dests.has(idx)){ctx.tryMove({from:selected,to:idx});return}const p2=state.cells[idx];const mine2=p2&&((youBlack&&(p2==="b"||p2==="B"))||(!youBlack&&(p2==="r"||p2==="R")));const canStart=all.some(m=>m.from===idx);ctx.setLocal({...state,selected:(mine2&&canStart)?idx:null})})}grid.appendChild(sq)})});wrap.appendChild(grid);root.appendChild(wrap)},
    status(state,seat){if(state.over)return state.over;const myTurn=(seat==="host"&&state.turn==="b")||(seat==="guest"&&state.turn==="r");return myTurn?"Your move.":"Their move."}
  };
  function squareIndex(r,c){return r*4+Math.floor(c/2)}
  function idxToRowCol(i){const r=Math.floor(i/4),k=i%4,c=r%2===0?k*2+1:k*2;return{r,c}}
  function pieceColor(p){if(!p)return null;return p==="b"||p==="B"?"b":"r"}
  function isKing(p){return p==="B"||p==="R"}
  function neighbors(i,p){const {r,c}=idxToRowCol(i);const dirs=[];if(p==="b"||isKing(p))dirs.push([-1,-1],[-1,1]);if(p==="r"||isKing(p))dirs.push([1,-1],[1,1]);const out=[];for(const[dr,dc] of dirs){const r1=r+dr,c1=c+dc;if(r1<0||r1>7||c1<0||c1>7)continue;if((r1+c1)%2===0)continue;out.push({r:r1,c:c1,i:squareIndex(r1,c1),dr,dc})}return out}
  function legalMovesFrom(cells,from){const p=cells[from];if(!p)return[];const color=pieceColor(p);const steps=[],jumps=[];for(const n of neighbors(from,p)){if(!cells[n.i])steps.push({from,to:n.i,caps:[]});else if(pieceColor(cells[n.i])!==color){const r2=n.r+n.dr,c2=n.c+n.dc;if(r2>=0&&r2<=7&&c2>=0&&c2<=7&&(r2+c2)%2===1){const land=squareIndex(r2,c2);if(!cells[land])jumps.push({from,to:land,caps:[n.i]})}}}const allJumps=[];const stack=jumps.map(j=>({...j,cells:applyCaps(cells,j)}));while(stack.length){const cur=stack.pop();const more=[];const occ=cur.cells;const p2=occ[cur.to];for(const n of neighbors(cur.to,p2)){if(occ[n.i]&&pieceColor(occ[n.i])!==color){const r2=n.r+n.dr,c2=n.c+n.dc;if(r2>=0&&r2<=7&&c2>=0&&c2<=7&&(r2+c2)%2===1){const land=squareIndex(r2,c2);if(!occ[land]){const next={from:cur.from,to:land,caps:cur.caps.concat(n.i)};more.push(next);stack.push({...next,cells:applyCaps(cells,next)})}}}}if(!more.length)allJumps.push({from:cur.from,to:cur.to,caps:cur.caps})}return allJumps.length?allJumps:steps}
  function applyCaps(cells,mv){const next=cells.slice();next[mv.to]=next[mv.from];next[mv.from]=null;mv.caps.forEach(c=>{next[c]=null});return next}
  function legalMoves(cells,color){const moves=[];cells.forEach((p,i)=>{if(p&&pieceColor(p)===color)moves.push(...legalMovesFrom(cells,i))});const jumps=moves.filter(m=>m.caps.length);return jumps.length?jumps:moves}
  function winnerCheckers(cells){const bHas=cells.some(p=>p==="b"||p==="B");const rHas=cells.some(p=>p==="r"||p==="R");if(!bHas)return"Red wins.";if(!rHas)return"Black wins.";if(!legalMoves(cells,"b").length)return"Red wins.";if(!legalMoves(cells,"r").length)return"Black wins.";return null}

  const FLEET=[{id:"carrier",name:"Carrier",len:5},{id:"battleship",name:"Battleship",len:4},{id:"cruiser",name:"Cruiser",len:3},{id:"submarine",name:"Submarine",len:3},{id:"destroyer",name:"Destroyer",len:2}];
  const Battleship={id:"battleship",title:"Battleship",
    newState(){return{phase:"place",host:{ships:{},shots:{},ready:false},guest:{ships:{},shots:{},ready:false},turn:"host",over:null,placing:{id:"carrier",vertical:false}}},
    apply(state,msg){const next=JSON.parse(JSON.stringify(state));if(msg.kind==="place"){if(next.phase!=="place"||next[msg.seat].ready)return state;next[msg.seat].ships[msg.ship]={cells:msg.cells};return next}if(msg.kind==="unplace"){if(next.phase!=="place"||next[msg.seat].ready)return state;delete next[msg.seat].ships[msg.ship];return next}if(msg.kind==="ready"){next[msg.seat].ready=true;if(next.host.ready&&next.guest.ready){next.phase="fire";next.turn="host"}return next}if(msg.kind==="shot"){if(next.phase!=="fire"||next.over||next.turn!==msg.seat)return state;const target=msg.seat==="host"?"guest":"host";if(next[msg.seat].shots[msg.cell])return state;const hit=isOccupied(next[target].ships,msg.cell);next[msg.seat].shots[msg.cell]=hit?"hit":"miss";if(hit&&fleetSunk(next[target].ships,next[msg.seat].shots))next.over=msg.seat==="host"?"Host wins.":"Guest wins.";else next.turn=target;return next}return state},
    render(root,state,ctx){root.innerHTML="";const me=ctx.seat,them=me==="host"?"guest":"host";const wrap=el("div","bs-layout");if(state.phase==="place"){const col=el("div","bs-col");col.appendChild(el("h3","","Your fleet"));const tools=el("div","bs-tools");FLEET.forEach(s=>{const chip=el("button","ship-chip"+(state.placing&&state.placing.id===s.id?" active":"")+(state[me].ships[s.id]?" done":""));chip.textContent=s.name+" ("+s.len+")";chip.addEventListener("click",()=>ctx.setLocal({...state,placing:{id:s.id,vertical:state.placing?state.placing.vertical:false}}));tools.appendChild(chip)});const rot=document.createElement("button");rot.className="btn small ghost";rot.textContent=state.placing&&state.placing.vertical?"Vertical":"Horizontal";rot.addEventListener("click",()=>{const p=state.placing||{id:"carrier",vertical:false};ctx.setLocal({...state,placing:{...p,vertical:!p.vertical}})});tools.appendChild(rot);col.appendChild(tools);col.appendChild(drawGrid({ships:state[me].ships,shots:{},showShips:true,onClick:cell=>placeShip(state,ctx,cell)}));const readyBtn=document.createElement("button");readyBtn.className="btn small primary";readyBtn.style.marginTop="10px";readyBtn.textContent=state[me].ready?"Waiting for them\u2026":"Ready";readyBtn.disabled=Object.keys(state[me].ships).length<5||state[me].ready;readyBtn.addEventListener("click",()=>ctx.tryMove({kind:"ready"}));col.appendChild(readyBtn);wrap.appendChild(col);const other=el("div","bs-col");other.appendChild(el("h3","",state[them].ready?"They are ready":"They are still placing"));other.appendChild(drawGrid({ships:{},shots:{},showShips:false,onClick:()=>{}}));wrap.appendChild(other)}else{const fire=el("div","bs-col");fire.appendChild(el("h3","","Their waters"));fire.appendChild(drawGrid({ships:{},shots:state[me].shots,showShips:false,sunk:sunkCells(state[them].ships,state[me].shots),onClick:cell=>{if(state.turn!==me||state.over)return;ctx.tryMove({kind:"shot",cell})}}));wrap.appendChild(fire);const own=el("div","bs-col");own.appendChild(el("h3","","Your waters"));own.appendChild(drawGrid({ships:state[me].ships,shots:state[them].shots,showShips:true,sunk:sunkCells(state[me].ships,state[them].shots),onClick:()=>{}}));wrap.appendChild(own)}root.appendChild(wrap)},
    status(state,seat){if(state.over){const winHost=state.over.startsWith("Host");if((winHost&&seat==="host")||(!winHost&&seat==="guest"))return"You sank their fleet.";return"Your fleet is gone."}if(state.phase==="place"){const me=state[seat].ready,them=state[seat==="host"?"guest":"host"].ready;if(me&&them)return"Battle begins.";if(me)return"Waiting for them to finish placing.";return"Place all five ships, then ready up."}return state.turn===seat?"Your shot.":"Incoming\u2026"}
  };
  function placeShip(state,ctx,cell){const me=ctx.seat;if(state[me].ready)return;const placing=state.placing||{id:"carrier",vertical:false};const spec=FLEET.find(s=>s.id===placing.id);if(!spec)return;if(state[me].ships[spec.id])ctx.tryMove({kind:"unplace",ship:spec.id});const cells=[];const x=cell%10,y=Math.floor(cell/10);for(let i=0;i<spec.len;i++){const cx=placing.vertical?x:x+i,cy=placing.vertical?y+i:y;if(cx>9||cy>9){toast("Doesn\u2019t fit there.");return}cells.push(cy*10+cx)}const occupied=new Set();Object.entries(state[me].ships).forEach(([id,sh])=>{if(id!==spec.id)sh.cells.forEach(c=>occupied.add(c))});if(cells.some(c=>occupied.has(c))){toast("Overlaps another ship.");return}ctx.tryMove({kind:"place",ship:spec.id,cells})}
  function isOccupied(ships,cell){return Object.values(ships).some(s=>s.cells.includes(cell))}
  function fleetSunk(ships,shots){return FLEET.every(s=>ships[s.id]&&ships[s.id].cells.every(c=>shots[c]==="hit"))}
  function sunkCells(ships,shots){const set=new Set();Object.values(ships).forEach(s=>{if(s.cells.every(c=>shots[c]==="hit"))s.cells.forEach(c=>set.add(c))});return set}
  function drawGrid({ships,shots,showShips,sunk,onClick}){const grid=el("div","bs-grid");const shipCells=new Set();if(showShips)Object.values(ships).forEach(s=>s.cells.forEach(c=>shipCells.add(c)));for(let i=0;i<100;i++){const cell=el("div","bs-cell");if(shipCells.has(i))cell.classList.add("ship");if(shots[i]==="hit")cell.classList.add("hit");if(shots[i]==="miss")cell.classList.add("miss");if(sunk&&sunk.has(i))cell.classList.add("sunk");cell.addEventListener("click",()=>onClick(i));grid.appendChild(cell)}return grid}

  return{tictactoe:TTT,chess:ChessGame,checkers:Checkers,battleship:Battleship,list:[ChessGame,Checkers,TTT,Battleship]}
})();
